### ISSUE TITLE
Ported to 4.0

### ISSUE THREAD

**Issue by elvisish** [mrezai/GodotStairs#4]
Here's a fork I ported to 4.0: https://github.com/elvisish/GodotStairs

**Comment by mrezai** [comment]
I think it's a good idea to add .godot folder to .gitignore in first commit and force push to get a smaller diff.

**Comment by elvisish** [comment]
> I think it's a good idea to add .godot folder to .gitignore in first commit and force push to get a smaller diff.

Sorry I'm absolutely awful at github/git and barely know what I'm doing, I was amazed I managed to get this far with it. Okay, so if I do that then re-push it should be smaller?

**Comment by elvisish** [comment]
> I think it's a good idea to add .godot folder to .gitignore in first commit and force push to get a smaller diff.

Okay I think I did it, see what you think.

**Comment by mrezai** [comment]
I did a fast check and it seems some files reverted to previous version, for example Player.gd is Godot 3 compatible now.
It isn't a good idea to force push to master but your fork is new so you can do something like this:

```
git reset --hard HEAD~2
git reset --soft HEAD~2
git reset -- .godot
#edit .gitignore file and add .godot/
git add .gitignore
git commit -m "Updated to Godot 4.0"
```

**Comment by elvisish** [comment]
> I did a fast check and it seems some files reverted to previous version, for example Player.gd is Godot 3 compatible now.
> 
> It isn't a good idea to force push to master but your fork is new so you can do something like this:
> 
> 
> 
> ```
> 
> git reset --hard HEAD~2
> 
> git reset --soft HEAD~2
> 
> git reset -- .godot
> 
> #edit .gitignore file and add .godot/
> 
> git add .gitignore
> 
> git commit -m "Updated to Godot 4.0"
> 
> git push --force
> 
> ```

I'm doing this from the GitHub desktop app as I am absolutely awful with git, I use it exclusively as a backup tool as I am the only one developing, how should I run these commands on windows?

**Comment by elvisish** [comment]
> I did a fast check and it seems some files reverted to previous version, for example Player.gd is Godot 3 compatible now. It isn't a good idea to force push to master but your fork is new so you can do something like this:
> 
> ```
> git reset --hard HEAD~2
> git reset --soft HEAD~2
> git reset -- .godot
> #edit .gitignore file and add .godot/
> git add .gitignore
> git commit -m "Updated to Godot 4.0"
> git push --force
> ```

Okay, I just remade the repo, it has ignore setup and should be okay now?

**Comment by mrezai** [comment]
> > I did a fast check and it seems some files reverted to previous version, for example Player.gd is Godot 3 compatible now.
> > It isn't a good idea to force push to master but your fork is new so you can do something like this:
> > ```
> > 
> > git reset --hard HEAD~2
> > 
> > git reset --soft HEAD~2
> > 
> > git reset -- .godot
> > 
> > #edit .gitignore file and add .godot/
> > 
> > git add .gitignore
> > 
> > git commit -m "Updated to Godot 4.0"
> > 
> > git push --force
> > ```
> 
> I'm doing this from the GitHub desktop app as I am absolutely awful with git, I use it exclusively as a backup tool as I am the only one developing, how should I run these commands on windows?

You could run commands by installing this and using git bash from installed tools:
https://git-scm.com/download/win

You can learn how to use git properly from this tutorial:
https://www.cduan.com/technical/git/
