### ISSUE TITLE
Godot 4?

### ISSUE THREAD

**Issue by ballerburg9005** [mrezai/GodotStairs#5]
Can this be done in Godot 4, or is it unfeasible/impossible?

I checked a few of the functions and classes used, like move_and_slide_with_snap, but they are not available in Godot 4. Which leads me to believe that porting this project was not done, because of limitations.

I suppose there is new and better stuff now in the engine for doing this, just don't know how.

I wish we had a way to simply replicate Quake movement accurately once and for all.

**Comment by mrezai** [comment]
You can find a port here that made by someone else: https://github.com/mrezai/GodotStairs/issues/4
I made a port myself but I should test it more before release it, maybe one or two month later because I'm busy now by remaking first level of DUSK for learning purpose!

**Comment by mrezai** [comment]
Project ported to Godot 4.
