### ISSUE TITLE
Ceiling interferes with stair step

### ISSUE THREAD

**Issue by Lamoot** [mrezai/GodotStairs#6]
Hello, first thank you for sharing your project, it's a very nice stair-stepping solution that works well in many situations. From the ones I tested, it's the most reliable and pleasant with regards to complex floor geometry.

I have a question though about a bug I encountered and whether it's something that can be easily fixed? In the attached video, I added a ceiling over one of the ramps. The ceiling is high enough so the player can walk underneath, but it prevents the stair step solution to work on the closest stair.

https://github.com/mrezai/GodotStairs/assets/3763179/0f20a7cc-00d3-4eba-87ad-d5399791ba48

- The ceiling is **1.810 m** above the highest stair of the ramp. This is the lowest height where the 1.8 m tall player can still walk underneath.
- The stair stepping solution again works properly when the ceiling is **2.017 m** high (difference of  **0.207 m**).
- Using the box collision shape.
- The provided cylinder shape requires even higher ceiling to work, **2.026 m**.
- Using Jolt physics.
- I'm using an otherwise unmodified project from this repository.

**Comment by mrezai** [comment]
Hello, thanks for your tests!
This isn't a bug, you could consider it as a trade-off for better performance. You can increase STEP_CHECK_COUNT for example to 7 to solve the issue.
The trade-off is you can choose smaller number for STEP_CHECK_COUNT and design levels based on STEP_HEIGHT_DEFAULT, I mean there should be at least this much empty space between player's head and ceiling all the times, but it's possible to increase STEP_CHECK_COUNT to check empty space incrementally and that'll increase CPU usage.

**Comment by Lamoot** [comment]
Ah right, increasing the STEP_CHECK_COUNT to 4 solves the issue. I'm going now with 2m tall ceilings which are still small enough to create tight corridors. The step count change and level design requirement to have the ceiling 0.2m above the player's 1.8 height are reasonable enough to follow.

Thanks for the quick reply and provided information :+1:
