### ISSUE TITLE
How to set upper surface height limit?

### ISSUE THREAD

**Issue by NilTPL** [mrezai/GodotStairs#8]
How would i go about solving this problem?
https://github.com/mrezai/GodotStairs/assets/76227208/2e6552bd-4764-4451-8f30-7530ad6b9269
The character snaps upwards purely based on if it can almost reach it, just enough for the stair snapping mechanism to proc, even if the obstacle is as tall as about two thirds of the character height

**Comment by NilTPL** [comment]
Perhaps i could repurpose it for a vaulting system...

**Comment by mrezai** [comment]
Please test this branch: https://github.com/mrezai/GodotStairs/tree/step_check_in_air

You can enable/disable stair stepping in air by setting `is_enabled_stair_stepping_in_air` or enable it and set `STEP_HEIGHT_IN_AIR_DEFAULT` to lower values.
If it doesn't make new bugs I'll merge it to master.

@Lamoot it seems you made a new scene for tests, please test this feature if you have time, thanks.

**Comment by NilTPL** [comment]
Much appreciated, many thanks! will test out this solution.

oh, in the meanwhile I have also noticed a typo in player.gd, you have written "sensitivity" as "sensetivity"

**Comment by NilTPL** [comment]
you can see for yourself here:
https://github.com/NilTPL/SampleFPS

**Comment by Lamoot** [comment]
@mrezai I tested the changes and couldn't find any bugs in my test level. Movement behaves nicely with either enabled or disabled `is_enabled_stair_stepping_in_air`.

Separating the step height value for floor and air also feels nice. Especially when I change `STEP_HEIGHT_IN_AIR_DEFAULT` to `(0, 0.1, 0)` it adds a nice margin to make more jumps successful.

@NilTPL I can't reproduce the issue from your videos. Can you provide a bit more information on the setup you have.
* is `is_enabled_stair_stepping_in_air` `true` or `false`?
* What collision shape for the player are you using. This project provides a box, cylinder, and a capsule. I'm using a cylinder and didn't test with other shapes.
* Just to make sure, you have Jolt physics enabled and are not using Godot's default physics?

**Comment by NilTPL** [comment]
@Lamoot 
i am using a Box shape,
i am using Jolt physics if i remember correctly,
i have only tested with air stepping disabled

as for reproducing the issue, you could try yourself as i shared my project on my github

**Comment by mrezai** [comment]
@NilTPL @Lamoot thanks for your tests.

@Lamoot capsule isn't supported yet because its bottom isn't flat so needs a different algorithm, a little explanation [here](https://www.reddit.com/r/godot/comments/194vqe2/godotstairs_a_poc_implementation_of_stair/)

@NilTPL I'd never tested this implementation using CSG nodes because these nodes were buggy in Godot 3.
I think using Qodot or even [Cyclops](https://github.com/blackears/cyclopsLevelBuilder) is better than using CSG even only for prototyping.
I'll test your linked project for CSG bugs but if it needs non-simple fixes I'll consider these nodes as unsupported and will add some documentation to README about it.

**Comment by Lamoot** [comment]
> @Lamoot capsule isn't supported yet because its bottom isn't flat so needs a different algorithm, a little explanation [here](https://www.reddit.com/r/godot/comments/194vqe2/godotstairs_a_poc_implementation_of_stair/)

I used a capsule collider in my project initially when I wasn't as familiar with the topic. I'm using cylinder now and I have no problems with it. Unless there's a strong benefit of using a capsule collider, there's probably no need for an additional algorithm.
